/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg3;

/**
 *
 * @author Brand
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opSuma = new javax.swing.JMenuItem();
        opResta = new javax.swing.JMenuItem();
        opMultiplicacion = new javax.swing.JMenuItem();
        opDivision = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout VentanaLayout = new javax.swing.GroupLayout(Ventana);
        Ventana.setLayout(VentanaLayout);
        VentanaLayout.setHorizontalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        VentanaLayout.setVerticalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jMenu1.setText("Operaciones");

        opSuma.setText("Suma");
        opSuma.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                opSumaMenuKeyTyped(evt);
            }
        });
        opSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSumaMouseClicked(evt);
            }
        });
        opSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSumaActionPerformed(evt);
            }
        });
        jMenu1.add(opSuma);

        opResta.setText("Resta");
        opResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRestaActionPerformed(evt);
            }
        });
        jMenu1.add(opResta);

        opMultiplicacion.setText("Multiplicación");
        opMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultiplicacionActionPerformed(evt);
            }
        });
        jMenu1.add(opMultiplicacion);

        opDivision.setText("División");
        opDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivisionActionPerformed(evt);
            }
        });
        jMenu1.add(opDivision);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");

        cerrar.setText("Cerrar programa");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jMenu2.add(cerrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRestaActionPerformed
        // TODO add your handling code here:
        Resta rest = new Resta();
        Ventana.add(rest);
        rest.setVisible(true);
    }//GEN-LAST:event_opRestaActionPerformed

    private void opSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSumaActionPerformed
        // TODO add your handling code here:
        Suma sum =new Suma();
        Ventana.add(sum);
        sum.setVisible(true);
    }//GEN-LAST:event_opSumaActionPerformed

    private void opMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultiplicacionActionPerformed
        // TODO add your handling code here:
        Multiplicacion mult = new Multiplicacion();
        Ventana.add(mult);
        mult.setVisible(true);
    }//GEN-LAST:event_opMultiplicacionActionPerformed

    private void opDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivisionActionPerformed
        // TODO add your handling code here:
        Division div =new Division();
        Ventana.add(div);
        div.setVisible(true);
    }//GEN-LAST:event_opDivisionActionPerformed

    private void opSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opSumaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_opSumaMouseClicked

    private void opSumaMenuKeyTyped(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_opSumaMenuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_opSumaMenuKeyTyped

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Ventana;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opDivision;
    private javax.swing.JMenuItem opMultiplicacion;
    private javax.swing.JMenuItem opResta;
    private javax.swing.JMenuItem opSuma;
    // End of variables declaration//GEN-END:variables
}
